# Site settings
title: Protocol v1.1 Viewer
baseurl: "/debugger-protocol-viewer-1.1"
url: "https://chromedevtools.github.io"
twitter_username: ChromeDevTools
github_username:  chromedevtools

collections:
  domains:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
    type: domains
  values:
    layout: default
